run:
  go: '1.23.4'
linters:
  enable:
    - thelper
    - gofumpt
    - tparallel
    - unconvert
    - wastedassign
    - tagliatelle

linters-settings:
  gofumpt:
    # Module path which contains the source code being formatted.
    # Default: ""
    module-path: github.com/liushunking/integrated_exporter
    # Choose whether to use the extra rules.
    # Default: false
    extra-rules: true
#  staticcheck:
#    checks: ["-SA5008"] # 忽略 tag 检查